import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { CarritoContext, CarritoProvider } from "@/context/CarritoContext";
import { UserProvider } from "@/context/userContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex flex-col">
          <UserProvider>
          <CarritoProvider>
                <Navbar/> 
                <main className="flex flex-grow justify-center container mx-auto px-4 py-8">{children}</main>
                <Footer/>    
          </CarritoProvider>
          </UserProvider>
        </div>
        </body>   
    </html>
  );
}
